### ISSUE TITLE
Refactor test scripts

### ISSUE THREAD

**Issue by Sharpie** [Sharpie/RTikZDevice#18]
The tikz testsuite is getting a little bit long in the tooth.  Specifically, two issues related to R 2.12.x should have been caught by the testsuite which would have removed the need for a 0.5.3 release:
- The test suite does not create it's own metrics dictionary that is separate from the user's normal dictionary.  This prevented testsuite metrics from being recalculated which ment that the developers never noticed all the new warning messages R 2.12.0 was spewing.
- The testsuite does a good job of checking to see that the tikzDevice works the way it should.  However, it does not check to see that the tikzDevice fails the way it should.  A check for failure could have shown that error messages were not being generated when they should have been.

Proposal:

Migrate the test scripts to a unit testing framework, such as Hadley's `test_that`.

Benefits:
- `test_that` provides excellent capabilities for isolating tests so that the actions and results of one test do not affect the execution of another test.
- `test_that` contains failure checks.  Tests can be designed to fail and the framework checks to see that the expected error/warning message is generated.

Comments?

**Comment by cameronbracken** [comment]
I agree that the test suite is unwieldy. I do see some pros and cons in using a traditional testing suite:

Pros:
- We can test in a much more manageable way like you say

Cons:
- Many of the things we originally created the suite to test for (such as string placement, or matching the output of another device) cannot be tested with simple assertions. 
- Many of the things we would like to test for (such as correct color values) are not exposed at the R level and so cant be tested with an R level test suite.
  
  Otherwise Im all for it.

**Comment by Sharpie** [comment]
Clean up old testing scripts, update README

The tikzDevice testing suite has now been re-implemented on top of test_that.
Some work remains to be done:
- Port tests that exercise XeLaTeX functionality.
- Implement regression checks via visual diffs using ImageMagick&#39;s `compare`
  tool.

Closed by d889fe6c4f74372345aad90404ee96ab91efe3df.
