### ISSUE TITLE
'bg' parameter is not respected during plot creation

### ISSUE THREAD

**Issue by cameronbracken** [Sharpie/RTikZDevice#31]
The following code demonstrates the bug:

```
tikz("try.tex", standAlone=TRUE)
 op<-par(bg=11,bty="n", cex=2, mar=c(3,4,1,2)+0.1)
 x <- runif(100)
 plot(x, las=1, yaxt="n",tcl=0, ann=F, type="l", lwd=2, col="blue")
 grid(col="white", lty="solid", nx=NA, ny=NULL, lwd=2)
 lines(x, col="blue", lwd=2)
 axis(1, tcl=0, labels=FALSE, col="black", lwd=1, at=as.Date(c("1970-01-01","2011-01-01")))
 axis(2, las=2, tick=FALSE)
 par(op)
dev.off()
```

There should be a green background but it is white. In addition, changing the tikz 'bg' parameter actually has no effect, it is never actually used in the code.

**Comment by Sharpie** [comment]
Looks like 2 things need to happen:
- `TikZ_Open` and `TikZ_NewPage` need to call `SetFill` and `SetAlpha` to set a fill color and use `\fill` instead of `\draw`.
- The drawing of the background needs to be delayed until the first call to a plotting function is made---that way the user has time to adjust the background using `par` after calling `tikz`.

**Comment by Sharpie** [comment]
![It's fixed!](https://d3nwyuy0nl342s.cloudfront.net/img/fb0a503006e12f3e682943ce395fcc4dffa630cf/687474703a2f2f696d61676573312e6d656d6567656e657261746f722e6e65742f496d6167654d6163726f2f363437363831302f646f6e742d62652d7361642d6974732d616c72656164792d66697865642e6a70673f696d61676553697a653d4d656469756d)

**Comment by cameronbracken** [comment]
lol woot!
